//
// Created by wpsimon09 on 06/10/24.
//

#ifndef GLOBALVULKANENUMS_HPP
#define GLOBALVULKANENUMS_HPP

enum PIPELINE_TYPE
{
    PIPELINE_TYPE_RASTER_BASIC,
};

enum QUEUE_FAMILY_INDEX_TYPE
{
    QUEUE_FAMILY_INDEX_GRAPHICS,
    QUEUE_FAMILY_INDEX_TRANSFER,
    QUEUE_FAMILY_INDEX_PRESENT,
    QUEUE_FAMILY_INDEX_COMPUTE
};

#endif //GLOBALVULKANENUMS_HPP