//
// Created by wpsimon09 on 06/10/24.
//

#ifndef GLOBALVULKANENUMS_HPP
#define GLOBALVULKANENUMS_HPP

enum PIPELINE_TYPE
{
    PIPELINE_TYPE_RASTER_PBR_TEXTURED,
    PIPELINE_TYPE_RTX,
};

enum QUEUE_FAMILY_INDEX_TYPE
{
    QUEUE_FAMILY_INDEX_GRAPHICS,
    QUEUE_FAMILY_INDEX_TRANSFER,
    QUEUE_FAMILY_INDEX_PRESENT,
    QUEUE_FAMILY_INDEX_COMPUTE
};

enum BUFFER_TYPE
{
    BUFFER_TYPE_VERTEX,
    BUFFER_TYPE_VERTEX_STAGING,
    BUFFER_TYPE_IMAGE,
    BUFFER_TYPE_IMAGE_STAGING,
    BUFFER_TYPE_INDEX,
    BUFFER_TYPE_INDEX_STAGING,
    BUFFER_TYPE_UNDEFINED
};


#endif //GLOBALVULKANENUMS_HPP